version: '3.1'
services:
   webserver:
     image: nginx:alpine
     volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
     container_name: webserver
     restart: unless-stopped
     ports: 
       - "27016:80"
       - "443:443"