#ifndef EMBED_RESOURCES_H
#define EMBED_RESOURCES_H

extern const unsigned char club_10_png[];
extern const unsigned club_10_png_size;
extern const unsigned char club_2_png[];
extern const unsigned club_2_png_size;
extern const unsigned char club_3_png[];
extern const unsigned club_3_png_size;
extern const unsigned char club_4_png[];
extern const unsigned club_4_png_size;
extern const unsigned char club_5_png[];
extern const unsigned club_5_png_size;
extern const unsigned char club_6_png[];
extern const unsigned club_6_png_size;
extern const unsigned char club_7_png[];
extern const unsigned club_7_png_size;
extern const unsigned char club_8_png[];
extern const unsigned club_8_png_size;
extern const unsigned char club_9_png[];
extern const unsigned club_9_png_size;
extern const unsigned char club_ace_png[];
extern const unsigned club_ace_png_size;
extern const unsigned char club_jack_png[];
extern const unsigned club_jack_png_size;
extern const unsigned char club_king_png[];
extern const unsigned club_king_png_size;
extern const unsigned char club_queen_png[];
extern const unsigned club_queen_png_size;
extern const unsigned char default_card_png[];
extern const unsigned default_card_png_size;
extern const unsigned char diam_10_png[];
extern const unsigned diam_10_png_size;
extern const unsigned char diam_2_png[];
extern const unsigned diam_2_png_size;
extern const unsigned char diam_3_png[];
extern const unsigned diam_3_png_size;
extern const unsigned char diam_4_png[];
extern const unsigned diam_4_png_size;
extern const unsigned char diam_5_png[];
extern const unsigned diam_5_png_size;
extern const unsigned char diam_6_png[];
extern const unsigned diam_6_png_size;
extern const unsigned char diam_7_png[];
extern const unsigned diam_7_png_size;
extern const unsigned char diam_8_png[];
extern const unsigned diam_8_png_size;
extern const unsigned char diam_9_png[];
extern const unsigned diam_9_png_size;
extern const unsigned char diam_ace_png[];
extern const unsigned diam_ace_png_size;
extern const unsigned char diam_jack_png[];
extern const unsigned diam_jack_png_size;
extern const unsigned char diam_king_png[];
extern const unsigned diam_king_png_size;
extern const unsigned char diam_queen_png[];
extern const unsigned diam_queen_png_size;
extern const unsigned char hear_10_png[];
extern const unsigned hear_10_png_size;
extern const unsigned char hear_2_png[];
extern const unsigned hear_2_png_size;
extern const unsigned char hear_3_png[];
extern const unsigned hear_3_png_size;
extern const unsigned char hear_4_png[];
extern const unsigned hear_4_png_size;
extern const unsigned char hear_5_png[];
extern const unsigned hear_5_png_size;
extern const unsigned char hear_6_png[];
extern const unsigned hear_6_png_size;
extern const unsigned char hear_7_png[];
extern const unsigned hear_7_png_size;
extern const unsigned char hear_8_png[];
extern const unsigned hear_8_png_size;
extern const unsigned char hear_9_png[];
extern const unsigned hear_9_png_size;
extern const unsigned char hear_ace_png[];
extern const unsigned hear_ace_png_size;
extern const unsigned char hear_jack_png[];
extern const unsigned hear_jack_png_size;
extern const unsigned char hear_king_png[];
extern const unsigned hear_king_png_size;
extern const unsigned char hear_queen_png[];
extern const unsigned hear_queen_png_size;
extern const unsigned char spad_10_png[];
extern const unsigned spad_10_png_size;
extern const unsigned char spad_2_png[];
extern const unsigned spad_2_png_size;
extern const unsigned char spad_3_png[];
extern const unsigned spad_3_png_size;
extern const unsigned char spad_4_png[];
extern const unsigned spad_4_png_size;
extern const unsigned char spad_5_png[];
extern const unsigned spad_5_png_size;
extern const unsigned char spad_6_png[];
extern const unsigned spad_6_png_size;
extern const unsigned char spad_7_png[];
extern const unsigned spad_7_png_size;
extern const unsigned char spad_8_png[];
extern const unsigned spad_8_png_size;
extern const unsigned char spad_9_png[];
extern const unsigned spad_9_png_size;
extern const unsigned char spad_ace_png[];
extern const unsigned spad_ace_png_size;
extern const unsigned char spad_jack_png[];
extern const unsigned spad_jack_png_size;
extern const unsigned char spad_king_png[];
extern const unsigned spad_king_png_size;
extern const unsigned char spad_queen_png[];
extern const unsigned spad_queen_png_size;
extern const unsigned char test_fs[];
extern const unsigned test_fs_size;
#endif
