name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: 1.39.18
        actions-cache-folder: 'emsdk-cache'
    - uses: actions/checkout@v3
    - name: Verify
      run: emcc -v
    - name: make
      run: make
    - name: upload build
      uses: actions/upload-artifact@v3
      with:
        name: Poker
        path: build\Release\Poker.exe
    - name: upload server
      uses: actions/upload-artifact@v3
      with:
        name: PokerServer
        path: buildServer\Release\PokerServer.exe
    - name: upload web
      uses: actions/upload-artifact@v3
      with:
        name: PokerWeb
        path: nginx docker
      
